### ISSUE TITLE
Server crashes when sending mail in SJIS

### ISSUE THREAD

**Issue by Misu-me** [Mezeporta/Erupe#11]
There is a problem that the server stops working when sending mail under the SJIS environment, as was the case with the Board a while ago.

![mail](https://user-images.githubusercontent.com/6690604/182035827-1d7512d6-4d43-4408-a3a8-3c54b19f8441.jpg)

In my environment, I have improved it by modifying the code as above.

**Comment by sekaiwish** [comment]
I implemented the conversion to UTF8 but accepting items still seems to crash the client, guess I'll have to look into this more.
