### ISSUE TITLE
Warehouse Rework (V2)

### ISSUE THREAD

**Issue by sekaiwish** [Mezeporta/Erupe#114]
[Branch](https://github.com/ZeruLight/Erupe/tree/feature/warehouse-v2)
# Delivery Cat in Garden 
https://web.archive.org/web/20191218060324/http://cog-members.mhf-z.jp/sp/manual/page168.html
Only those who are using the Extra Course will be able to deposit items with the delivery cat and share items between characters in the same account and on the same server.

* Deposited items can be shared between characters in the same account and on the same server.

* Items can be deposited, excluding equipment. However, some items cannot be deposited. Items that cannot be deposited will be displayed in gray on the selection screen and cannot be selected.

* "Items that can be obtained in the G class" can only be received or deposited if the character meets the conditions for participation in the G class.

* If the expiration date of the Extra Course expires after depositing, you will not be able to use the home delivery cat, but the deposited items will continue to be stored. You can continue to use it by purchasing the Extra Course again.

# Blacksmith Warehouse
https://web.archive.org/web/20191218060307/http://cog-members.mhf-z.jp/sp/manual/page172.html
The "Additional Warehouse" can only be used within 12 hours and up to a certain number of times, and to use it, you must be enrolled in the Hunter Life Course.

Also, if you try to use it more than a certain number of times, the next time you can use it will be displayed.

# Guild Item Box
https://web.archive.org/web/20191218060306/http://cog-members.mhf-z.jp/sp/manual/page217.html

- The maximum number of items that can be placed in the initial shared item box is 100. The upper limit will increase as you increase the rank of clan.
- Unlike the item box in My House, the placement of items is automatically rearranged each time you access it.
- The Shared Item Box can only be used by one person at a time.
- Selling an item in the shared item box the Zenny you get from the sale will be given to the hunter who sold it

# Actions needed for 9.2 migration

- [ ] Reset of user and guild box

**Comment by sekaiwish** [comment]
Warehouses do not function as intended, non-functional on older versions. Warehouses extend to Guild/Clan item box and Account-wide item box.

**Comment by stratic-dev** [comment]
![Image](https://github.com/ZeruLight/Erupe/assets/6687129/0f8bf7de-babe-40b5-ae09-13ec91ebac45)
