### ISSUE TITLE
Can't claim daily netcafe gift

### ISSUE THREAD

**Issue by TsuyaC** [Mezeporta/Erupe#49]
**Description**:
After updating to [commit](https://github.com/ZeruLight/Erupe/commit/8326e22d9f666e13770cc52c411c7a29c1b102e2) after rights-v3, cannot claim daily netcafe gift anymore after using `!course` command to enable netcafe course. Tried with multiple course combinations (*excluding nboost*) and only hunterlife + netcafe. Claiming the daily gift still works with previous value for netcafe course (0x40000202).

**Reproduction Steps**:
1. From hunterslife course only, enable netcafe course via `!course netcafe`
2. Exit game
3. Restart game and join a world
4. Talk to "General Store" npc
5. Select "NetCafe Benefits" and confirm
6. Select "Daily Gift" and confirm

**Screenshots**
Ingame message when trying to claim daily gift:

![image](https://user-images.githubusercontent.com/94976487/199357169-1f19d261-86b5-42cb-851a-871cea3fbe4c.png)

**Additional context**
Launcher: Launcher V3
Client Patch: CT3 - Meta V1

**Comment by TsuyaC** [comment]
Can also not accept quests that have netcafe course as a requirement.

![image](https://user-images.githubusercontent.com/94976487/199360131-a4e6ecb4-01c2-4076-8d72-e9f35d906fa7.png)

**Comment by sekaiwish** [comment]
I assume this is because I changed it to not require that bit set all the way out at 2^30. I guess it really does require that massive value set.

**Comment by sekaiwish** [comment]
Fixed in latest commit.
