### ISSUE TITLE
GachaName does not support Japanese

### ISSUE THREAD

**Issue by Misu-me** [Mezeporta/Erupe#54]
Garbled text when displaying the gacha list in gacha cat.
This can be tentatively addressed by changing A to B.

handlers_shop_gacha.go
func handleMsgMhfEnumerateShop

A
resp.WriteUint32(0) // only 0 in known packet
stringBytes := append([]byte(gachaName), 0x00)
resp.WriteUint8(byte(len(stringBytes)))

↓
B
resp.WriteUint32(0) // only 0 in known packet
stringBytes := append([]byte(stringsupport.UTF8ToSJIS(gachaName)))
resp.WriteUint8(byte(len(stringBytes)))
resp.WriteBytes(stringBytes)

![image](https://user-images.githubusercontent.com/6690604/202853560-673806d2-a4c2-478c-bd18-6b4dc6b63adf.png)

**Comment by sekaiwish** [comment]
This is going to take a long time but [fix/shop-enum](https://github.com/ZeruLight/Erupe/tree/fix/shop-enum) will fix this.

**Comment by sekaiwish** [comment]
Merged the branch, fixed.
