### ISSUE TITLE
Raviente Support Deliveries not working as intended

### ISSUE THREAD

**Issue by ghost** [Mezeporta/Erupe#90]
**Description**:
When playing Support during a Great Slaying, the sedation/resurrection support deliveries do not work as intended.

**Reproduction Steps**:
1. Sedation support is requested, the first 50 Tranquilizers are delivered, and sedation support is carried out.
2. Sedation support is requested a 2nd time, but the total tranquilizers delivered stays over 50 and delivering additional increments of 50 does not resend sedation support at all.
3. Even different types of support such as resurrection support delivery do not work as intended after the first delivery.

**Screenshots**
![mhf_gfBOAVQ556](https://github.com/ZeruLight/Erupe/assets/112596053/400ba613-dbb2-40a8-bdfc-6c3fa6dc7280)
![mhf_cZwxVom4zV](https://github.com/ZeruLight/Erupe/assets/112596053/c44c3287-c3b0-4551-933d-b5eeaa4ff9aa)

**Additional context**
Based on the footage below, the counter for Tranquilizers, etc. delivered should be reset once support has been successfully carried out and is requested again: https://youtu.be/grE1Mn7eEKM?si=BLjRHwa3-cdJJZaB&t=1862

Please let me know if any additional data is needed.

**Comment by sekaiwish** [comment]
This affected all versions that use simplified Support (Normal and Violent types).
I fixed and simplified the code used for this in https://github.com/ZeruLight/Erupe/commit/0f2edbf0286d97e74c7359f78df032e31859c7ae.
Can you verify that the commit applied fixes the issues? Thanks.

**Comment by legayacruise** [comment]
Thanks for looking into this Wish, the soonest I'll be able to test this is Friday evening but I will test it then and report back!

**Comment by legayacruise** [comment]
I tested with another person the new commit,

Screenshots below are from after the first support delivery is carried out; tested on normal Ravi - support deliveries work as intended (counter resets upon subsequent deliveries and support is always carried out successfully:

![mhf_MZdgUOPlvS](https://github.com/ZeruLight/Erupe/assets/112596053/6c8f9332-e7bd-4ba4-9b05-13d731e834d1)
![mhf_bJ2eKsE4eR](https://github.com/ZeruLight/Erupe/assets/112596053/4b5cbcdf-f982-4d2b-bbe5-59a2bf243cb5)
![vlc_k7mcg3R1gQ](https://github.com/ZeruLight/Erupe/assets/112596053/0b5981f6-b8bc-4705-b0b3-06f3a39a8055)
![mhf_fsq3aT3scK](https://github.com/ZeruLight/Erupe/assets/112596053/df240b80-7a9f-4f2c-be00-83c6621cbec9)

Thank you once more for investigating and fixing this, Wish!
